### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by Palladinium** [asweigart/scrollart#1]
Hi, I recently found https://scrollart.org and I love what you've built!

I was wondering if you had thought of explicitly licensing the source code in this repo - you mention it's intended for education, but it's not clear to me what I'm allowed to do with it. What are you comfortable with regarding the reuse or adaptation of this code, and modifying or displaying the ASCII art it generates?

I understand it might be intended more as artwork than code, so if you don't want it copied or modified feel free to tell me to bugger off! Just thought I'd ask :smiley:

**Comment by MarketingPip** [comment]
@asweigart - any chance you could chime in on this?

**Comment by asweigart** [comment]
I've added a GPLv3 license. I'm completely open to this work being free to share and modify. If there's any need for use not allowed by the GPL, you can reach out to me for an exception that I'll almost certainly grant. Thanks! And sorry for the delay in these replies.

**Comment by MarketingPip** [comment]
@asweigart - I have ported some of your original code and was hoping to possibly commit back to this repo (to expand to your ports). 

That said - I was hoping to make a little library (JS) for scroll art (if not all the patterns / designs you have done on the website).

Plus - was hoping to grab reuse the scroll art logic into another cool open source library for making more animation relating things. (Once I publish it as a usable library).

Not really sure if me porting your DOM versions etc - doing a complete re-write is considered technically falling under GPL-3 copyleft etc... But just wanted to run it by you - when I seen this open! (assuming you will be more then cool with it) :D

**Comment by merwok** [comment]
Can I ask how/where you added the GPL? There are no commits for this in this repo.
