### ISSUE TITLE
Forbiddenzone.py Issue: Remains Stuck in Running Loop,

### ISSUE THREAD

**Issue by yousefabuz17** [asweigart/scrollart#2]
When executing the'forbiddenzone.py', the program gets stuck in a loop displaying the message "standby" indefinitely.

**Comment by asweigart** [comment]
Sorry for the delay in this. This program is intended to be controlled by forbiddenzonecontrol.py, which writes to a file that forbiddenzone.py is constantly reading to know when to switch between scenes. It's a hack, but it worked well enough for my schedule at the time.
